from openai.types.responses import Response as OpenAIResponse
from openai.types.responses import ResponseInputParam as OpenAIResponseInputParam
from openai.types.responses import ResponseOutputMessage as OpenAIResponseOutputMessage
from openai.types.responses import ResponseStreamEvent as OpenAIResponseStreamEvent

Response = OpenAIResponse
ResponseStreamEvent = OpenAIResponseStreamEvent
ResponseOutputMessage = OpenAIResponseOutputMessage
ResponseInputParam = OpenAIResponseInputParam
